basePath: /v1/
definitions:
  entity.ChatRoomEntity:
    properties:
      chat_room_id:
        type: string
      chat_room_name:
        type: integer
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /v1/chatroom:
    post:
      consumes:
      - application/json
      description: Create Chat room
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.ChatRoomEntity'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Create Chat room
      tags:
      - createRoom
swagger: "2.0"
