// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type ChatRoom struct {
	ChatRoomID   uuid.UUID
	ChatRoomName int32
}

type Message struct {
	MessageID        uuid.UUID
	Content          string
	CreatedAt        time.Time
	FkParticipantsID uuid.UUID
	FkChatRoomID     uuid.UUID
	LikeMessage      int32
}

type Notification struct {
	NotificationID uuid.UUID
	CreatedAt      time.Time
	Message        string
	FkChatRoomID   uuid.UUID
	FkMessageID    uuid.UUID
}

type Participant struct {
	ParticipantsID uuid.UUID
	Name           string
	ChatRoomID     uuid.UUID
}

type Subscriber struct {
	SubscriberID     uuid.UUID
	SubscribedAt     time.Time
	FkParticipantsID uuid.UUID
	FkChatRoomID     uuid.UUID
}
