// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"github.com/google/uuid"
)

type ChatRoom struct {
	ChatRoomID   uuid.UUID
	ChatRoomName int32
}

type Participant struct {
	ParticipantsID uuid.UUID
	Name           string
	ChatRoomID     uuid.UUID
}
